### ISSUE TITLE
External Links Warning

### ISSUE THREAD

**Issue by luke-** [humhub/legal#50]
Optional Feature:

Ideally: An external link should be identified as such. Ideally, this would be done by automatically adding a corresponding icon behind the link. If not possible: 

- Perform check after the user clicks
- If external link, delay the opening of the external page. Instead, open Lightbox with notice "You are leaving this page and will be redirected to an external page". Automatic forwarding after 5 seconds.

**Comment by yurabakhtin** [comment]
@luke- Sorry, it is not clear where the external links can be defined in this module `legal`.
Maybe you mean to search links inside the content before print it, i.e. we find all links inside content and if it is an external then add to the link a confirmation dialog.

But you wrote about "check after the user clicks", it seems you want to check somehow by JS or AJAX?

**Comment by luke-** [comment]
@yurabakhtin The wording "check after click" is a bit misleading, especially after we ideally want to display an icon/symbol behind it beforehand as well.

- After the page has been rendered (onReady or similar)
- Search via JS for A tags with external Href (not the base URL, with a different domain).
- Add an icon after the LinkText, if that is not possible trigger a Confirm modal after click.

**Comment by luke-** [comment]
@Semir1212 Can you please check the Wording?

**Comment by Semir1212** [comment]
@yurabakhtin 

External Link

This link leads to an external website. Would you like to proceed? 

Cancel // Proceed

**Comment by yurabakhtin** [comment]
@luke- @Semir1212 Commit https://github.com/humhub-contrib/legal/pull/53/commits/b987ed3300f7097a0ec9cc0a5af9206516987a6f:

![wording](https://user-images.githubusercontent.com/6995524/178464653-ad6bf3d5-fa84-400d-9193-3cc6ab54aa5f.png)

**Comment by luke-** [comment]
@yurabakhtin it already looks good. Can you please make this feature optional and extend it to posts/comments.
![image](https://user-images.githubusercontent.com/4736168/178469864-d6d98858-3116-4ac0-909a-390c4247c7ce.png)
![image](https://user-images.githubusercontent.com/4736168/178469990-9c56ebf3-09f2-4f9a-a6b9-23051bf5446f.png)

**Comment by yurabakhtin** [comment]
@luke- The content of legal page was rendered by `RichText::output($content)`. I have extended this only for the module `legal`.

If we need the same for posts and comments, does it mean I should move the new code from the `legal` into core in order to extend the `RichText` widget with options like `RichText::output($content, ['externalLinks' => [...]])`, and then remove the duplicated code the `legal` module?

If yes, what core branch should be updated, `develop`?

**Comment by yurabakhtin** [comment]
@luke- Yes, the markdown of the richtext is rendered really by JS, so my current solution was done here https://github.com/humhub-contrib/legal/pull/53/files#diff-124ba9b0f8c3920fc7d0e3202f8627a95c2ad97b5591702c56fc43ce20c4af98 by JS, so if I will move this solution in the core then it will be moved here https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/resources/js/humhub.ui.richtext.prosemirror.js#L155 or some additional file that will extends the JS widget `RichText`.

**Comment by luke-** [comment]
I don't quite understand that right now, what exactly do you want to transfer into the Core? The external link marker?

**Comment by yurabakhtin** [comment]
@luke- If you need the same feature from current PR should be applied to core posts/comments then almost all JS code from the file `resources/js/humhub.legal.js` - https://github.com/humhub-contrib/legal/pull/53/files#diff-124ba9b0f8c3920fc7d0e3202f8627a95c2ad97b5591702c56fc43ce20c4af98 should be moved to core.

**Comment by luke-** [comment]
@yurabakhtin Hmm, I actually don't like that if such module logic comes into the core. 

What is the reason why we can't leave this external?

The module could just inject its javascript on each page and work on the OnReady/PjaxReady events?

**Comment by yurabakhtin** [comment]
@luke- Ah now I got you, we need to inject it for posts and comments from the module `legal`, ok I will implement this.

**Comment by luke-** [comment]
Ok, so there should be no changes from the core.
