### ISSUE TITLE
Is it a trouble? error: "The script resource is behind a redirect, which is disabled"

### ISSUE THREAD

**Issue by tosintech-web** [humhub/legal#76]
When a new user sign up and humhub system shows a "Terms and Conditions" page, these error are displayed on browser's onsole.

![スクリーンショット 2024-06-28 215709](https://github.com/humhub-contrib/legal/assets/75475434/f55cb546-5f88-4e34-a7f5-d1b71b7c475d)

Is it something trouble?

**Comment by luke-** [comment]
Can you please provide steps to reproduce?
